env: "dev"

server:
  host: "0.0.0.0"
  port: "8080"

weather:
  api_type: openweathermap
  apis:
    openweathermap:
      url: "https://api.openweathermap.org/data/2.5"
      key: "your_openweathermap_key"
    gismeteo:
      url: "https://api.gismeteo.net/v2/weather/current"
      key: "your_gismeteo_api_key"

maps:
  api_type: "starline"
  apis:
    google:
      url: "https://maps.googleapis.com/maps/api/"
      key: "your_google_maps_key"
    yandex:
        url: "https://geocode-maps.yandex.ru/1.x/"
        key: "your_yandex_maps_key"
    starline:
        url: "https://starline-online.ru/api/"
        key: "your_starline_key"

cache:
  type: "in-memory"
  ttl: "300s"

log:
  level: debug
  label: weather-service
  add_timestamp: "yes"
  time_format: "02/01/2006 15:04:05 MST"
  prefix: ""
  add_source: "yes"
  formatter: "text"
  source_format: "short"
  enable_fx_logs: "no"
